// <auto-generated />
using LabLog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LabLog.Migrations
{
    [DbContext(typeof(EventModelContext))]
    [Migration("20170928082432_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("LabLog.Domain.Events.LabEvent", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventBody");

                    b.Property<string>("EventType");

                    b.Property<Guid>("RoomId");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Version");

                    b.HasAlternateKey("RoomId");

                    b.ToTable("LabEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
