// <auto-generated />
using LabLog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LabLog.Migrations
{
    [DbContext(typeof(EventModelContext))]
    [Migration("20171003105445_eventAuthor")]
    partial class eventAuthor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("LabLog.Domain.Events.LabEvent", b =>
                {
                    b.Property<Guid>("RoomId");

                    b.Property<int>("Version");

                    b.Property<string>("EventAuthor");

                    b.Property<string>("EventBody");

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("RoomId", "Version");

                    b.ToTable("LabEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
