// <auto-generated />
using LabLog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace LabLog.Migrations
{
    [DbContext(typeof(RoomModelContext))]
    partial class RoomModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("LabLog.Models.ComputerModel", b =>
                {
                    b.Property<string>("SerialNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ComputerNumber");

                    b.Property<string>("Room");

                    b.Property<string>("RoomModelName");

                    b.HasKey("SerialNumber");

                    b.HasIndex("RoomModelName");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("LabLog.RoomModel", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("LabLog.Models.ComputerModel", b =>
                {
                    b.HasOne("LabLog.RoomModel")
                        .WithMany("Computers")
                        .HasForeignKey("RoomModelName");
                });
#pragma warning restore 612, 618
        }
    }
}
